### ISSUE TITLE
Cannot Deploy a gateway name while tls_passthrough is set to true

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/zos#1906] opened 2023-02-19 15:45 UTC
Whenever I try to deploy a gateway name with a tls_passthrough set to true it fails giving me a ```failed to parse backend: parse "[300:170b:469a:2ed8:788f:6dd6:b647:8ed6]:443": first path segment in URL cannot contain colon``` error 

![gateway](https://user-images.githubusercontent.com/66883096/219958542-d8598be2-d4a7-49b5-8bed-6d7e82680f7a.png)

My GatewayNameModel setup is as follows:
- The planetary IP belongs to one of my deployed Vms. 
```bash
 const gw = new GatewayNameModel();
    gw.name = "test";
    gw.node_id = +(await grid3.capacity.filterNodes(gatewayQueryOptions))[0].nodeId;
    gw.tls_passthrough = true;
    gw.backends = ["[300:170b:469a:2ed8:788f:6dd6:b647:8ed6]:443"];
```

**Comment by xmonader** [comment] 2023-02-19 19:36
@rawdaGastan is this the one that needs to be `//IP:443`  same as https://github.com/threefoldtech/zos/issues/1886 ? if so @maayarosama please change the backends tline to be
```
    gw.backends = ["//[300:170b:469a:2ed8:788f:6dd6:b647:8ed6]:443"];
```

**Comment by rawdaGastan** [comment] 2023-02-20 09:41
yes same issue and it will work with @xmonader suggestion

**Comment by muhamadazmy** [comment] 2023-02-21 08:04
@rawdaGastan I was discussing the correct fix for this issue with @xmonader . Let me know if he explained to you otherwise I can re-explain

**Comment by xmonader** [comment] 2023-02-22 13:00
closed as duplicate of https://github.com/threefoldtech/zos/issues/1886

**Closed as completed by xmonader** 2023-02-22 13:00 UTC
Labels: type_bug
