### ISSUE TITLE
failed to install k3s: could not run vm

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1193] opened 2021-02-21 12:31 UTC
with normal vdc deployments now getting this error 

example workloads:

```
failed to install k3s: could not run vm: iGMAmat/nsonOtKz8ZxF+NhZVpxoI5j7B5CToQhFqaFgPisrpfRdqLwEDeOHjZvYiG6WznaRKbjM37h0ttewIi6lbzR8nIObD/9OXEGCUTgfQ5pShT5Q3skvjcimX/El7qrQLHVvdUvNzhoC9w4P8oNabtmPVX9nNx94RrcTt5w8dNTKLz+FIWb6esQTFtYFhOfY5YgshmYne6p3AnIU3Z+r8Wdc3HakcOs3Po+9 root@waleed-ng" net_eth0=10.200.3.2/24,10.200.3.1,10.200.0.0/16,fd4a:774d:4439:3::2/64,fd4a:774d:4439:3::1,priv net_dns=8.8.8.8,1.1.1.1,2001:4860:4860::8888 virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6 virtio_mmio.device=4K@0xd0002000:7 [ 0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers' [ 0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers' [ 0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers' [ 0.000000] x86/fpu: xstate_offset[2]: 576, xstate_sizes[2]: 256 [ 0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format. [ 0.000000] BIOS-provided physical RAM map: [ 0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable [ 0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000cfffffff] usable [ 0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000012fffffff] usable [ 0.000000] NX (Execute Disable) protection: active [ 0.000000] DMI not present or invalid. [ 0.000000] Hypervisor detected: KVM [ 0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00 [ 0.000000] kvm-clock: cpu 0, msr 2e01001, primary cpu clock [ 0.000000] kvm-clock: using sched offset of 39922555 cycles [ 0.000009] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns [ 0.000021] tsc: Detected 1999.998 MHz processor [ 0.000187] last_pfn = 0x130000 max_arch_pfn = 0x400000000 [ 0.000251] Disabled [ 0.000255] x86/PAT: MTRRs disabled, skipping PAT initialization too. [ 0.000273] CPU MTRRs all blank - virtualized system. [ 0.000281] x86/PAT: Configuration [0-7]: WB WT UC- UC WB WT UC- UC [ 0.000287] last_pfn = 0xd0000 max_arch_pfn = 0x4000: failed to spawn vm machine process '31242-1'"
```

- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/31242
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/31214
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/31186

also seems all of these failures happened on the same node `BBmMHCw392RLiByVEUT2ac6y6qJpbW9xj8TRdgk5rMGN`

also 

- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/30885
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/30882
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/30881
happened on thursday with `failed  to spawn vm machine process` and on the same node as well  `BBmMHCw392RLiByVEUT2ac6y6qJpbW9xj8TRdgk5rMGN`

**Comment by xmonader** [comment] 2021-02-21 14:43
also 

- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/30885
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/30882
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/30881
happened on thursday with `failed  to spawn vm machine process` and on the same node as well  `BBmMHCw392RLiByVEUT2ac6y6qJpbW9xj8TRdgk5rMGN`

**Comment by LeeSmet** [comment] 2021-02-21 15:04
Seems on the node, firecracker processes starting die due `traps: fc_vcpu 0[16740] trap invalid opcode ip:49b58c sp:7f224f3c14f0 error:0 in firecracker[400000+166000]`. The `ip` is always the same, `sp` differs slightly

**Comment by LeeSmet** [comment] 2021-02-22 11:41
obj dissassemble shows that this is actually an `UD2` instruction as part of a panic function. The panic message is not captured however.

It also seems the cache filled up at some point on the node, resulting in possible corruption. After this is resolved, we need to check if the issue is still there.

**Comment by weynandkuijpers** [comment] 2021-02-23 07:45
@LeeSmet or @xmonader This issue is being worked on but sits in backlog.  I'll push it to  profess, but then you have to make this work for this release

**Comment by maxux** [comment] 2021-02-23 09:35
Should be fixed later by https://github.com/threefoldtech/zos/issues/1194

**Comment by sasha-astiadi** [comment] 2021-02-23 09:36
still on problem finding phas this week, move it as part of 2.6

**Comment by DylanVerstraete** [comment] 2021-03-05 12:21
Moving to verification because the fix is now live on devnet

**Comment by sasha-astiadi** [comment] 2021-03-12 11:34
any update @xmonader

**Closed as completed** 2021-03-23 16:36 UTC
Labels: type_bug
