### ISSUE TITLE
failed to apply provision: not enough free resources to support this memory size

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#1118] opened 2020-12-09 14:39 UTC
I'm getting this error when deploying containers on nodes that should have enough memory to deploy. (I thought we can overprovision cpu and memory).

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/515672
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/515702
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/515704
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/515706
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/515721

**Comment by waleedhammam** [comment] 2020-12-10 10:08
also at this one: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/516390

**Comment by m-motawea** [comment] 2020-12-21 08:58
still getting the error on testnet when the node have enough resources
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/522463

![image](https://user-images.githubusercontent.com/32568986/102758491-7b15d980-437b-11eb-9b6b-b624442512b4.png)

**Comment by muhamadazmy** [comment] 2020-12-21 11:12
Yes, it seem the reserved 2G that are reserved to the system were not reported to the explorer correctly. It's already fixed but the fix was not deployed to testnet. I am working on a RC now to roll this fix to testnet.

**Comment by waleedhammam** [comment] 2020-12-24 15:34
It's still happening on testnet on the node `72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib`
wid: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/524098

![Screenshot from 2020-12-24 17-33-38](https://user-images.githubusercontent.com/10658229/103096906-2e95fc80-460e-11eb-80dc-1811f10ee6b7.png)

**Comment by mhost39** [comment] 2021-01-17 11:12
It still happening on testnet on the node Hx4B6B8s8yQ5ABLStma1kZ33kCuprSxzU8tY4totKbWH
wid: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/678
![image](https://user-images.githubusercontent.com/31102305/104838700-53a42500-58c5-11eb-98db-1e21b115712c.png)

**Comment by DylanVerstraete** [comment] 2021-01-19 09:35
> It still happening on testnet on the node Hx4B6B8s8yQ5ABLStma1kZ33kCuprSxzU8tY4totKbWH
> wid: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/678

I just tried this myself: 

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/1385

Seems to be working just fine.

![Screenshot from 2021-01-19 10-34-39](https://user-images.githubusercontent.com/17138347/105015561-f681ae00-5a41-11eb-8237-cce6e7dafeca.png)


@mhost39 can you please retry? :)

**Comment by muhamadazmy** [comment] 2021-01-21 09:21
A new fix has been deployed on both devnet and testnet, that fixes some discrepancy in memory calculations. Hence the issue is in verification

**Closed as completed** 2021-03-05 12:00 UTC
Labels: type_bug
