### ISSUE TITLE
IPV6 public configuration lost over time

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/zos#838] opened 2020-06-18 08:22 UTC
deployed network : 9988 OK
deployed k3s : 9989: OK
but some nodes are not reachable, even they are ok in kubectl
```
hteibler@skull:/mnt/c/NextCloud/G-IT/code/ge-tools$ kubectl describe nodes | grep "InternalIP"
  InternalIP:  10.76.13.2
  InternalIP:  10.76.14.2
  InternalIP:  10.76.16.2
  InternalIP:  10.76.11.2
  InternalIP:  10.76.17.2
  InternalIP:  10.76.12.2
  InternalIP:  10.76.15.2
  InternalIP:  10.76.10.2

hteibler@skull:/mnt/c/NextCloud/G-IT/code/ge-tools$ fping 10.76.{10..17}.2
10.76.10.2 is alive
10.76.11.2 is alive
10.76.12.2 is alive
10.76.13.2 is alive
10.76.17.2 is alive
10.76.14.2 is unreachable
10.76.15.2 is unreachable
10.76.16.2 is unreachable

$ fping 10.76.{10..17}.1
10.76.10.1 is alive
10.76.11.1 is alive
10.76.12.1 is alive
10.76.13.1 is alive
10.76.17.1 is alive
10.76.14.1 is unreachable
10.76.15.1 is unreachable
10.76.16.1 is unreachable
```
![image](https://user-images.githubusercontent.com/24313736/84996326-639c3080-b14d-11ea-9f96-f75c6a62087a.png)

**Comment by joefoxton** [comment] 2020-06-25 15:34
@rkhamis Just checking in here. What are our next steps to resolve?

**Comment by joefoxton** [comment] 2020-06-26 13:25
Any ideas about what might cause this? Unfortunately we can't easily reproduce as the reservation is long gone.

**Comment by delandtj** [comment] 2020-06-30 16:17
myeah... I've been looking around in that net, and there are 2 things that were intermixed:
1) at first, I was dismissing this issue as a remnant from the fact that the user issued the same access config to multiple colleagues, and that we could close it.
2) on second (further inspection) it seemed that the aggregator node (the one with ipv4) didn't properly reconfigure the ipv6 part of the interface that is used as entry-point for the ipv6 connectivity of the other Network Resources. fixed that by hand to stabilize the active networks

**Comment by zaibon** [comment] 2020-07-01 06:47
Re-opening to track the bug found by @delandtj

**Comment by zaibon** [comment] 2020-07-06 08:06
Can't reproduce the problem, And in v0.4 networkd will even stop messing with public config after boot so this bug is even less likely to appear.

**Closed as completed by zaibon** 2020-07-06 08:06 UTC
Labels: type_bug
