### ISSUE TITLE
Can't reach the cluster with public ip

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/zos#1128] opened 2020-12-17 16:17 UTC
After deploying VDC on devnet, I can't ping public IP

- wid: [https://explorer.devnet.grid.tf/api/v1/reservations/workloads/9424](https://explorer.devnet.grid.tf/api/v1/reservations/workloads/9424)
- [https://explorer.devnet.grid.tf/api/v1/reservations/workloads/9425](https://explorer.devnet.grid.tf/api/v1/reservations/workloads/9425)
- public IP: `185.69.167.125` 
- from master
```
k3os-26248 [~]$ ip a show eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 82:cf:51:e8:62:e5 brd ff:ff:ff:ff:ff:ff
    inet 185.69.167.125/24 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 2a02:1802:5e:0:80cf:51ff:fee8:62e5/64 scope global dynamic mngtmpaddr 
       valid_lft 15449sec preferred_lft 15449sec
    inet6 fe80::80cf:51ff:fee8:62e5/64 scope link 
       valid_lft forever preferred_lft forever

```

**Comment by DylanVerstraete** [comment] 2020-12-17 16:52
Investigating, looks like the node never set the response for the public ip reservation:

```
"data_json": {
     "id": "",
     "ip": ""
},
```

**Comment by muhamadazmy** [comment] 2020-12-18 11:16
The ip reservation [9424](https://explorer.devnet.grid.tf/api/v1/reservations/workloads/9424)  results is empty, the IP was not provisioned correctly, hence the VM should not have been created with this reservation. it seem that the node did not process this IP reservation. On that case the reservation must be released, and re-creaed.

I wil check out why the node did not process this reservation though

**Comment by muhamadazmy** [comment] 2020-12-18 11:32
Okay, so this reservation was before implementing the firewalling feature in ZOS. hence the only way to fix the situation now is to decomission all workloads related this IP and try again.

**Comment by LeeSmet** [comment] 2020-12-18 12:13
The only thing the firewalling does is add restrictions in the public interface, though icmp packets (for ipv4) are not dropped. Regardless, __everything__ was allowed before that patch was merged, meaning the issue seems to be the vm is no longer responding on the public interface.

Also note that we don't have access inside of the VM.

For similar issues in the future, please create a fresh vm with a similar setup (regarding network, public IP), and then verify that something is not working as intended (i.e. not responding to pings in this case). This way, it is immediately clear if this is a problem on our end, or if something went wrong inside the VM.

**Comment by ashraffouda** [comment] 2020-12-20 11:48
I got the same issue right after I deployed the cluster  today
```
[-] start: Error: Kubernetes cluster unreachable: Get "https://185.69.167.122:6443/version?timeout=32s": dial tcp 185.69.167.122:6443: connect: no rout
e to host
```
 the kubernetes master workload https://explorer.devnet.grid.tf/api/v1/reservations/workloads/10669
 the ip workload https://explorer.devnet.grid.tf/api/v1/reservations/workloads/10668
 I can reach it through private ip `10.200.2.2`

**Comment by DylanVerstraete** [comment] 2020-12-21 08:53
> 185.69.167.122

I can ping the public IP, can you try to ssh to it?

**Comment by ashraffouda** [comment] 2020-12-21 10:45
![Screenshot from 2020-12-21 12-43-36](https://user-images.githubusercontent.com/1689456/102768680-36de0580-438a-11eb-8ce1-808464ee1b58.png)

maybe the ip got reused by some else?

**Comment by DylanVerstraete** [comment] 2020-12-21 10:51
Looks like nobody is using the IP right now..

**Comment by DylanVerstraete** [comment] 2020-12-21 10:54
Also IP is not pingable anymore. Please retry and see if you can reproduce.

**Comment by LeeSmet** [comment] 2020-12-21 11:06
Ok so on a vm with pub IP we just commisioned on devnet we can ping the vm once it is commissioned:
```
⚡100% 🕙[ 12:00:49 ] ❯ ping 185.69.167.123
PING 185.69.167.123 (185.69.167.123) 56(84) bytes of data.
64 bytes from 185.69.167.123: icmp_seq=1 ttl=54 time=20.3 ms
64 bytes from 185.69.167.123: icmp_seq=2 ttl=54 time=20.4 ms
64 bytes from 185.69.167.123: icmp_seq=3 ttl=54 time=21.9 ms
64 bytes from 185.69.167.123: icmp_seq=4 ttl=54 time=20.7 ms
64 bytes from 185.69.167.123: icmp_seq=5 ttl=54 time=20.2 ms
64 bytes from 185.69.167.123: icmp_seq=6 ttl=54 time=20.7 ms
^C
--- 185.69.167.123 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5007ms
rtt min/avg/max/mdev = 20.191/20.676/21.901/0.579 ms
```

The fact that you can't ping that IP right now is expected as it was not marked as deployed at the time. After looking at the reservation ids and checking logs, it seems the IP has been decommissioned and recommissioned at least after your initial deployment, as a result of an empty pool. This is expected behavior: when the pool can't sustain the public IP anymore, the interface serving this IP is disconnected. 

Because all resources used also are already clean up, we can't really do any meaningful investigation. For future deployments, when you find an issue, please make sure there is sufficient capacity in the pool to sustain the workloads for an extended amount of time. This will make sure we have sufficient time to investigate the state the workloads are in

**Comment by muhamadazmy** [comment] 2020-12-21 12:07
Can we close this issue?

**Comment by DylanVerstraete** [comment] 2020-12-21 12:09
let's test this is on devnet first

**Comment by abom** [comment] 2021-01-05 08:23
I cannot reach the cluster with public IP too

* IP worload: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16541
* K8s worload: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16542
* Public IP: 185.69.167.134


```
k3os-29739 [~]$ ip a show eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 26:8e:ed:22:18:71 brd ff:ff:ff:ff:ff:ff
    inet 185.69.167.134/24 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::248e:edff:fe22:1871/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by LeeSmet** [comment] 2021-01-05 09:46
So, from what I can tell, the vm was created around `Sun Jan  3 09:47:36 PM CET 2021`. Given that the issue is only reported now, I assume connectivity was initially fine. The public and private tap interface are present and in the expected state on the host. The machine log (k3os login splash screen thingy) does show that the IP's have been configured correctly. When running a tcpdump on the public tap, whilest running a ping to the public IP, echo requests can be seen coming in as expected, but no reply is going out. This leads me to believe the problem originates inside the vm itself.

At this point, further debugging would require having access to the private network and addition of our ssh keys to the vm so we can log in to the vm itself and verify the state it is in

**Comment by LeeSmet** [comment] 2021-01-05 14:33
seems the vm was not handling arp replies on the pub iface anymore, meaning it didnt know how to reach the deft gw. It is currently unknown if this is due to a bug in the hypervisor or in the kernel of the guest.

A reboot (restart of the hypervisor) fixed the issue. For now

**Comment by sasha-astiadi** [comment] 2021-01-06 10:15
lee: we need to wait until it happens again to continue investigating, 
I Put this issue as blocked, milestone later, and remove from project grid 2.4

**Comment by xmonader** [comment] 2021-01-06 21:09
another incident while I was able to use the cluster without problems using the public ip it suddenly became unreachable

```
root@waleed-ng:~/js-sdk# ping 10.200.0.2
PING 10.200.0.2 (10.200.0.2) 56(84) bytes of data.
64 bytes from 10.200.0.2: icmp_seq=1 ttl=63 time=103 ms
64 bytes from 10.200.0.2: icmp_seq=2 ttl=63 time=102 ms
^C
--- 10.200.0.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 102.279/102.801/103.324/0.613 ms
root@waleed-ng:~/js-sdk# ping 10.200.0.2^C
root@waleed-ng:~/js-sdk# ping 185.69.167.133 
PING 185.69.167.133 (185.69.167.133) 56(84) bytes of data.
From 84.199.193.14 icmp_seq=1 Destination Host Unreachable
From 84.199.193.14 icmp_seq=2 Destination Host Unreachable
From 84.199.193.14 icmp_seq=3 Destination Host Unreachable
```

in the explorer  https://explorer.devnet.grid.tf/api/v1/farms
```
{
address: "185.69.167.133/24",
gateway: "185.69.167.1",
reservation_id: 0
},
not sure what reservation_id 0 means but seems should have been set to another value

```
- the kubernetes reservation https://explorer.devnet.grid.tf/api/v1/reservations/workloads/17021

- vdc kubernetes section
```
JS-NG> v.kubernetes                                                                                                                           
[KubernetesNode(
  role=<KubernetesRole.MASTER: 'master'>,
  public_ip='185.69.167.133',
  _size=15,
  ip_address='10.200.0.2',
  wid=17021,
  node_id='qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3',
  pool_id=2733
), KubernetesNode(
  role=<KubernetesRole.WORKER: 'worker'>,
  public_ip='::/128',
  _size=16,
  ip_address='10.200.2.2',
  wid=17026,
  node_id='3NAkUYqm5iPRmNAnmLfjwdreqDssvsebj4uPUt9BxFPm',
  pool_id=2733
)]


```

![image](https://user-images.githubusercontent.com/64129/103819853-e9dd7d00-5073-11eb-865d-bafbbf930ae6.png)

**Comment by xmonader** [comment] 2021-01-06 21:11
> lee: we need to wait until it happens again to continue investigating,
> I Put this issue as blocked, milestone later, and remove from project grid 2.4

@sasha-astiadi  this issue is quite serious. Should stay in 2.4 as it's happening already couple of times now. Hopefully this one gives you a chance to debug @LeeSmet

**Comment by LeeSmet** [comment] 2021-01-06 21:18
@xmonader for this one, the ip becoming unreachable is correct as the pool expired. This results in the network for the public IP being cleaned up. The main issue with this one is that the other workloads such as the kubernetes vm are not properly cleaned up. I'll investigate the reason why that happens when I can, but otherwise it seems that in this case the outcome is as expected

**Comment by xmonader** [comment] 2021-01-06 21:51
Hmmm  https://explorer.devnet.grid.tf/api/v1/reservations/pools/2733 seems the pool has cus, sus 
![image](https://user-images.githubusercontent.com/64129/103822996-d8976f00-5079-11eb-9bab-6a5a8b4f5565.png)
```
pool_id: 2733,
cus: 2116367.75,
sus: 399086.49,
ipv4us: 0,
```


also now it seems someone took the ip in another reservation

```
address: "185.69.167.133/24",
gateway: "185.69.167.1",
reservation_id: 17069
```

**Comment by LeeSmet** [comment] 2021-01-06 22:32
mm when I looked when I wrote my previous comment, I _thought_ I saw 0 values for cus, sus and ipv4us. Regardless, even in the state in your comment there are 0 ipv4us, so it is correct that the access to the public IP was removed. If the pool still had some cus and sus left, then the behavior we are noticing is as expected: ipv4 is empty and thus public network access is removed, but the vm is still alive. 

As for someone else now having the IP: if the ip is not reserved, it is ofcourse available to claim for anyone to start using it

**Comment by xmonader** [comment] 2021-01-06 23:02
I'm actually not sure, we have code the extends the pools after the successful deployment (but that's triggered when the cus, sus, ip4us aren't enough for 2 weeks)

I deployed a fresh VDC just to make sure of the pool resources (because the one in the prev comment was also a fresh one) and it started with `1208294` ipv4us which is enough for 13.9 days

**Comment by sasha-astiadi** [comment] 2021-01-20 14:02
remove from 2.4 until it reoccurs again

**Comment by DylanVerstraete** [comment] 2021-03-05 11:59
Closing becasue this issue is not occurring anymore at this time. Can be reopened if it happens again.

**Closed as completed by DylanVerstraete** 2021-03-05 11:59 UTC
Labels: type_bug
