### ISSUE TITLE
Networkd does not release ports when a NR is removed

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#484] opened 2020-01-15 10:44 UTC
as a result, deploying the same network after it has expired fails until networkd is restarted

**Comment by zaibon** [comment] 2020-01-15 14:49
I would like to have a way to reproduce or a test that fails and how the problem.
Cause the code is there: https://github.com/threefoldtech/zos/blob/master/pkg/network/networker.go#L428

**Comment by DylanVerstraete** [comment] 2020-03-13 09:07
Cannot reproduce

**Comment by zaibon** [comment] 2020-03-17 21:22
duplicate of #556

**Closed as completed by zaibon** 2020-03-17 21:22 UTC
Labels: type_bug, process_duplicate
