### ISSUE TITLE
"failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd",

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1037] opened 2020-10-29 13:46 UTC
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/494762

**Comment by LeeSmet** [comment] 2020-10-29 16:04
So it seems storaged thinks the amount of reserved space on the SSD does not allow further reservations: 

`debug usage of pool 18d7ef4e-cf2f-4877-bafc-a280a359fd7a max size=480103981056 new size=489894707200 reserved=489626271744`

Upon further investigation, it seems that there is 275GB of space reserved on the SSD, which roughly matches the 271 SRU the explorer reports. However, there is also an unlimited qgroup which currently uses up about 157GB. Since this is not a limited qgroup, storaged computes the reserved size here as the exact size it is currently using. This leads storaged to account for rouhly 432 GB of "reserved" space. At this point we are still missing some space, as 432 GB translates to `463856467968` bytes, still slightly less than reported by the above log line.

As per above, it also seems vdisks might not be included in the counters exposed in the explorer

Edit: as per manual count, `464367591424` bytes are reserved going from the qgroups, which should be the same storaged does

**Comment by LeeSmet** [comment] 2020-10-29 16:53
I forgot to account for the zdb namespaces. Given that there are indeed a few of those, I think its safe to assume that the reserved size reported by storaged is correct and that this is just a counter issue

**Comment by DylanVerstraete** [comment] 2020-10-30 10:33
Seems like relying on the cache to report these values is not good. Instead we should contact the responsible deamons to report the values.

- Containerd can report MRU and CRU
- Storaged can report SRU and HRU

When provisiond boots, we contact these 2 deamons and get the values. For the remaining time that provisiond runs we can increment / decrement these stats in memory like we are doing now.

**Comment by LeeSmet** [comment] 2020-10-30 13:43
Further investigation has revealed that there are quite a lot of subvolumes present which should not be here anymore (as the reservation has moved to state deleted). These reservations are properly removed from cache. Since the counters work on the cached reservations, and storaged works on actual data from disk, this explains why storaged seems to think the disk is fully reserved. It seems the cleanup flow needs to be checked, as well as the cleanup worker which runs every day

**Comment by m-motawea** [comment] 2020-11-04 13:30
the problem still exists on testnet on this node `A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7`

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/498382
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/498346

trying to find nodes by capacity returns
```
JS-NG> zos = j.sals.zos.get()                                                                            
JS-NG> nodes = zos.nodes_finder.nodes_by_capacity(71, sru=1)  
JS-NG> for n in nodes: 
     2     print(n.node_id)  
BDhpLyV28Y6Njy54WnB2Rkn6eHdEUbMu3GwTTs65rGAG
A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7
2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6
93qJrfeBqYiuVC973n9kPX79uA4rZU6oHL9pdJGBegHL
DNav25NSCpx8NHwX11CUoUMsr2VW42sGoFCx6dtxyMV9
2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz
DyuhYMRR5c6PCPYTaFGpoN5iheo87ubKRvsLzinBzHHJ
FDQJLM3NJCMzSdvb1qbigzotBg2WgSyLCJQFRAAyAP5e
2tzdPqM5xrFHkn264GHyUzXQda9UxFGcWMR9BeN54FTi
8BFWcddW79cawvjnuUMw8M5s9FqS3pHhMHvzn3pgCUiB
GLyFeBes9meAxfW44HhRHJGL9yR1i4oxUHrkqvA7UTSP
72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib
D1sY7tgHX6fVvjrpCotr4SmezVyRShLTufqhEpBQxK1v
3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF
6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ
2fi9ZZiBGW4G9pnrN656bMfW6x55RSoHDeMrd9pgSA8T
```

![image](https://user-images.githubusercontent.com/32568986/98117531-96538500-1eb2-11eb-819f-dd8644e268dc.png)

**Comment by muhamadazmy** [comment] 2020-11-04 13:52
Will investigate and update here with the findings

**Comment by muhamadazmy** [comment] 2020-11-04 14:30
Here are the findings so far:
- This machine have 2 disks (one HDD, and one SSD)
- The SSD disk is completely allocated, hence this is why this reservation fails on deployment (not the reservation is asking for SSD storage for the container rootfs)

- So the problem is still that the capacity reported is not actually the real consumed values on the disk. I think this is still duo to reliance on the cached values of consumed capacity rather than using the actual values reported by the daemons. 

I think it's time we implement [this](#issuecomment-719474840)

**Comment by muhamadazmy** [comment] 2020-11-04 14:30
Meanwhile is it possible that you start using HRUs instead of SRUs ?

**Comment by muhamadazmy** [comment] 2020-11-04 14:58
I found out that there is a lingering `vdisk` of 100GB on the SSD disk that does not have a corresponding reservation in the Cache. I think this should not exist already and cleanup process should take care of it 

@DylanVerstraete ?

**Comment by muhamadazmy** [comment] 2020-11-04 15:58
Linked to https://github.com/threefoldtech/zos/issues/1044

**Comment by muhamadazmy** [comment] 2020-11-06 11:33
I will keep it open until the fix is confirmed on testnet

**Comment by muhamadazmy** [comment] 2020-11-10 09:22
@m-motawea We have yet another fix on test-net. The fix is to make sure to have a better clean up process, to avoid leaking resources. could you give it another try on testnet.

**Comment by xmonader** [comment] 2020-11-12 10:30
happened again today 
![image](https://user-images.githubusercontent.com/64129/98928749-d3d39600-24e2-11eb-9c57-989adf7c14f1.png)

```
Workload 502203 failed to deploy due to error failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/502203
```

**Comment by muhamadazmy** [comment] 2020-11-12 16:17
Fixed in RC7 which is now on testnet. Please validate the fix is working for you

**Comment by ranatrk** [comment] 2020-11-30 10:25
Got the same error again trying to deploy on testnet for node `6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ`:

`Workload 512026 failed to deploy due to error failed to allocate storage: failed to create sub-volume: Not enough space left in pools of this type ssd. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/512026`


![image](https://user-images.githubusercontent.com/17128393/100598184-0ebd3280-3307-11eb-8483-375c7eed2cdb.png)

**Comment by AhmedHanafy725** [comment] 2020-11-30 10:30
Got the same error too on testnet on node `72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib`
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/512035

**Comment by muhamadazmy** [comment] 2020-11-30 12:04
So it seems there are some vdisks that do not get cleaned up 
![image](https://user-images.githubusercontent.com/10920323/100608317-db81a000-3314-11eb-8523-04cc9ace84a4.png)

```
[+] provisiond: 2020-11-30T11:24:07Z info skipping vdisk id=489885-1 vdisk=489885-1-vda
[+] provisiond: 2020-11-30T11:24:07Z info skipping vdisk id=506711-1 vdisk=506711-1-vda
[+] provisiond: 2020-11-30T11:24:07Z info skipping vdisk id=507920-1 vdisk=507920-1-vda
[+] provisiond: 2020-11-30T11:24:07Z info skipping vdisk id=509077-1 vdisk=509077-1-vda
[+] provisiond: 2020-11-30T11:24:07Z info skipping vdisk id=511149-1 vdisk=511149-1-vda
```

while the reservation are set to `deleted` but they are skipped by the cleaner. so we  need to find why.

**Comment by muhamadazmy** [comment] 2020-11-30 13:40
It's fixed on the faulty node but need an RC for this fix to be available on all testnet nodes . One is planned soon

**Comment by muhamadazmy** [comment] 2020-11-30 13:43
Reopen until verified on testnet

**Comment by xmonader** [comment] 2020-12-01 08:01
@muhamadazmy i just tried to create a volume on testnet and it failed with  `Not enough space left in pools of this type ssd` http://explorer.testnet.grid.tf/api/v1/reservations/workloads/512959

**Closed as completed** 2021-01-14 14:55 UTC
Labels: type_bug, priority_major
