### ISSUE TITLE
provisiond: try to provision the same workload twice in 1 second

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#922] opened 2020-09-07 10:43 UTC
```
[+] provisiond: 2020-09-07T10:24:29Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=475694-1 tag= to-delete=false type=zdb
[+] provisiond: 2020-09-07T10:24:30Z error failed to apply provision error="failed to ensure zdb containe running: failed to prepare zdb network: address already in use" id=475694-1
[+] provisiond: 2020-09-07T10:24:30Z error failed to provision reservation 475694-1 error="failed to ensure zdb containe running: failed to prepare zdb network: address already in use"
[+] provisiond: 2020-09-07T10:24:30Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=475694-1 tag= to-delete=false type=zdb
[+] provisiond: 2020-09-07T10:24:30Z error failed to apply provision error="failed to ensure zdb containe running: failed to prepare zdb network: address already in use" id=475694-1
[+] provisiond: 2020-09-07T10:24:30Z error failed to provision reservation 475694-1 error="failed to ensure zdb containe running: failed to prepare zdb network: address already in use"
```

**Comment by zaibon** [comment] 2020-09-30 15:29
More occurrence of the problem: https://github.com/threefoldtech/zos/issues/910#issuecomment-701332924

**Comment by DylanVerstraete** [comment] 2020-10-23 07:15
@zaibon issue still relevant?

**Comment by zaibon** [comment] 2020-10-23 07:23
yes, I've not seen any code going in to fix this.

**Comment by DylanVerstraete** [comment] 2020-10-23 07:45
Cannot reproduce though, also seems like #940 should have fixed it no?

**Comment by zaibon** [comment] 2020-10-23 07:52
I don't think so no. #940 only make it possible to re-send the same result for an already provisioned workload. Which maybe is enough but for sure doesn't change the fact that the same workload can be received in a very short period

**Comment by muhamadazmy** [comment] 2020-10-26 08:57
I will just state some facts here that I am sure you are fully aware of, but just to try logically resolve this:
- The provision engine is completely sequential. basically means that it process single reservation at a time
- Results of a reservation is cached, so next time the same reservation is received, the result will be returned immediately 
- If the same reservation is queued 2 (or more) times immediately after each other, only the 1st one is applied, but it **should** never cause a race condition due to the sequential nature of the engine.
- If the same reservation was queued 2 (or more) times it's probably caused by the explorer, hence we might be looking in the wrong place.
- Another possible cause of the issue if the provisiond daemon is running 2 instances on the same node. Hence a race would be possible (logs does not include process pid) while I don't see how this is possible, but should be considered as a possibility.

So, I would still recommend to put this issue on hold but if it was detected again we need to do the following:
- Make sure to get a full copy of the logs (update the issue with newer logs)
- Make sure we inspect the node itself that it doesn't  have
  - multiple provisiond instances running
  - cache disk corruption 
  - other failed daemons

**Comment by zaibon** [comment] 2020-10-26 09:00
The problem is not that the workload is provisionned twice, the code does not allow this. This bug is not dangerous at all for the normal flow. But it is showing the way we do polling is somehow flawed. 

I've set low lever priority cause it really doesn't matter much.

**Comment by DylanVerstraete** [comment] 2021-03-05 12:09
Closing in favor of grid 3.0 and the new provision engine

**Closed as completed by DylanVerstraete** 2021-03-05 12:09 UTC
Labels: type_bug, priority_minor
