### ISSUE TITLE
Node unresponsive and generating huge provisiond log volume

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2117] opened 2023-11-17 21:46 UTC
We had a report from a user that some nodes which appear to be online did not accept workloads. When investigating the issue, I found that one of these nodes is dumping huge amounts of provisiond logs and did not respond to RMB requests.

Node id is 2066. [Log link](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnetwork%3D%5C%22production%5C%22,node%3D%5C%225EoheyGaWEvqH8on4hw8i6DUTMpvFkUJjRAPnn7oXqDpW2V5%5C%22%7D%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221700205805000%22,%22to%22:%221700249005000%22%7D%7D).

![image](https://github.com/threefoldtech/zos/assets/17682591/e77e823d-90a8-4a5c-8e9f-1a21cfc03bd9)

That's 10k+ lines per minute of stuff that looks more or less like this:

```
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/threefoldtech/zbus@v1.0.1/object.go:226 +0x21e
2023-11-17 22:22:31	
[-] provisiond: created by github.com/threefoldtech/zbus.(*Stream).Run
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00049dfe8 sp=0xc00049dfe0 pc=0x467061
2023-11-17 22:22:31	
[-] provisiond: runtime.goexit()
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/threefoldtech/zbus@v1.0.1/object.go:232 +0xbb fp=0xc00049dfe0 sp=0xc00049df18 pc=0x713edb
2023-11-17 22:22:31	
[-] provisiond: github.com/threefoldtech/zbus.(*Stream).Run.func1()
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/reflect/value.go:2096 +0x68 fp=0xc00049df18 sp=0xc00049dec0 pc=0x497d88
2023-11-17 22:22:31	
[-] provisiond: reflect.Value.Recv({0xf51660?, 0xc000ac83c0?, 0x0?})
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/reflect/value.go:2116 +0x130 fp=0xc00049dec0 sp=0xc00049de68 pc=0x497f50
2023-11-17 22:22:31	
[-] provisiond: reflect.Value.recv({0xf51660?, 0xc000ac83c0?, 0x0?}, 0x0?)
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/chan.go:724 +0x25 fp=0xc00049de68 sp=0xc00049de40 pc=0x460545
2023-11-17 22:22:31	
[-] provisiond: reflect.chanrecv(0x0?, 0x0?, 0x0?)
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/chan.go:583 +0x49b fp=0xc00049de40 sp=0xc00049ddb0 pc=0x406cdb
2023-11-17 22:22:31	
[-] provisiond: runtime.chanrecv(0xc000ac83c0, 0xc000ce5980, 0x1)
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/proc.go:363 +0xd6 fp=0xc00049ddb0 sp=0xc00049dd90 pc=0x4388f6
2023-11-17 22:22:31	
[-] provisiond: runtime.gopark(0x0?, 0xc00049de30?, 0xbf?, 0xd5?, 0xc00049df28?)
2023-11-17 22:22:31	
[-] provisiond: goroutine 86 [chan receive]:
2023-11-17 22:22:31	
[-] provisiond: 
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/work/zos/zos/pkg/primitives/statistics.go:261 +0xfb
2023-11-17 22:22:31	
[-] provisiond: created by github.com/threefoldtech/zos/pkg/primitives.(*statsStream).ReservedStream
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x467061
2023-11-17 22:22:31	
[-] provisiond: runtime.goexit()
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/work/zos/zos/pkg/primitives/statistics.go:275 +0x2e fp=0xc00005bfe0 sp=0xc00005bfc0 pc=0xe0ce4e
2023-11-17 22:22:31	
[-] provisiond: github.com/threefoldtech/zos/pkg/primitives.(*statsStream).ReservedStream.func2()
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/work/zos/zos/pkg/primitives/statistics.go:264 +0x12c fp=0xc00005bfc0 sp=0xc00005bea0 pc=0xe0cfac
2023-11-17 22:22:31	
[-] provisiond: github.com/threefoldtech/zos/pkg/primitives.(*statsStream).ReservedStream.func1({0x1685c98, 0xc00044cb00})
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/select.go:328 +0x7bc fp=0xc00005bea0 sp=0xc00005bd60 pc=0x44813c
2023-11-17 22:22:31	
[-] provisiond: runtime.selectgo(0xc00005bf88, 0xc00005bee0, 0x719d5d?, 0x0, 0x5?, 0x1)
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/proc.go:363 +0xd6 fp=0xc00005bd60 sp=0xc00005bd40 pc=0x4388f6
2023-11-17 22:22:31	
[-] provisiond: runtime.gopark(0xc00005bf88?, 0x2?, 0x0?, 0x30?, 0xc00005bee4?)
2023-11-17 22:22:31	
[-] provisiond: goroutine 85 [select]:
2023-11-17 22:22:31	
[-] provisiond: 
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/threefoldtech/zbus@v1.0.1/server.go:217 +0xa5
2023-11-17 22:22:31	
[-] provisiond: created by github.com/threefoldtech/zbus.(*BaseServer).Start
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x467061
2023-11-17 22:22:31	
[-] provisiond: runtime.goexit()
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/threefoldtech/zbus@v1.0.1/server.go:217 +0x3e fp=0xc000060fe0 sp=0xc000060f98 pc=0x71aa7e
2023-11-17 22:22:31	
[-] provisiond: github.com/threefoldtech/zbus.(*BaseServer).Start.func1()
2023-11-17 22:22:31	
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/threefoldtech/zbus@v1.0.1/server.go:144 +0x105 fp=0xc000060f98 sp=0xc000060ee8 pc=0x719ac5
2023-11-17 22:22:31	
[-] provisiond: github.com/threefoldtech/zbus.(*BaseServer).worker(0xc000060fd0?, {0x1685c98, 0xc000135b80}, 0x1685c98?, 0xc00044cb00?, 0xc000912900, 0xc00048d350)
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/select.go:328 +0x7bc fp=0xc000060ee8 sp=0xc000060da8 pc=0x44813c
2023-11-17 22:22:31	
[-] provisiond: runtime.selectgo(0xc000060f60, 0xc000060f28, 0xc000618180?, 0x0, 0x405a7d?, 0x1)
2023-11-17 22:22:31	
[-] provisiond: 	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/proc.go:363 +0xd6 fp=0xc000060da8 sp=0xc000060d88 pc=0x4388f6
2023-11-17 22:22:31	
[-] provisiond: runtime.gopark(0xc000060f60?, 0x2?, 0x0?, 0x0?, 0xc000060f2c?)
2023-11-17 22:22:31	
[-] provisiond: goroutine 114 [select]:
```

**Comment by muhamadazmy** [comment] 2023-11-20 12:28
On panic, the go runtime prints the stack of all routines scheduled or running so while it's a lot it's only one of these that caused the crash

I found this (which is the cause of the crash)
![image](https://github.com/threefoldtech/zos/assets/10920323/1d6a6755-ca37-4020-af59-5e0c474deb5d)

followed by the stack that actually caused the failure here
![image](https://github.com/threefoldtech/zos/assets/10920323/e4d79c7f-0e2d-4320-8f91-68d23bec70e3)


And it seems unfortunately this happens in `BoltDB`. It's not the first time that I see Bolt causes similar memory crashes and a reboot won't fix it because the db file itself is now corrupt.

This is why we had some checks to validate the rrd db before to make sure it's not broken in that way. But it seems this can happen also under other circumstances. So I will update the checks of that.

The problem is even if fixed, this won't reach production before sometime. The node will not be reachable during this time. 

We have 2 options here
- Patch mainnet (i do not recommend) 
- Completely wipe the node (this means loss of node identity) it will register as a new node 
- If possible to delete a single file from the node disks i can guide you through the process to delete the faulty file for now. the node should not be affected

**Comment by muhamadazmy** [comment] 2023-11-20 12:48
I noticed that this farm has only this node. It might be easier for the farmer to erase the node and start over. I would recommend doing this after minting so he doesn't lose any.

If the farmer can access the disks (may be by booting ubuntu) the ssd disk will have a subvolume called `zos-cache` under there you can safely delete the file `modules/provisiond/metrics-diff.bolt`

**Closed as completed** 2023-11-20 12:56 UTC

**Comment by scottyeager** [comment] 2023-11-20 19:15
Understood. We weren't in contact with the farmer yet, since the report came from the user side. Also is a certified node, so manual fix would not generally be possible without return to vendor. No problem to wait for the fix to roll down to mainnet in this case.
