### ISSUE TITLE
failed to download kube config due to error [Errno None] Unable to connect to port 22 on 185.69.167.162

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1150] opened 2021-01-14 05:40 UTC
![image](https://user-images.githubusercontent.com/64129/104549560-cef2a600-563b-11eb-9cf3-bd344428e745.png)

happend on testnet and I assume related to https://github.com/threefoldtech/zos/issues/1149

**Comment by LeeSmet** [comment] 2021-01-14 15:26
As far as I see that IP is currently not reserved. I'll need at least a reservation ID to be able to find more info.

This is actually unrelated to 1149

**Comment by xmonader** [comment] 2021-01-14 16:45
Sorry @LeeSmet got distracted with something else when creating the issue

This is the ip workload
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/303
and these are all the workloads of the user
https://explorer.testnet.grid.tf/api/v1/reservations/workloads?customer_tid=94

**Comment by LeeSmet** [comment] 2021-01-15 15:01
Checking the node logs around the time of the problem shows that the host itself had some networking issues. These problems where not found on other nodes, suggesting it was specific for this node:

```
 [+] provisiond: 2021-01-14T05:38:50Z error failed to get reservation, retry same error="error while retrieving workloads from explorer: Get \"https://explorer.testnet.grid.tf/api/v1/reservations/nodes/8zPYak76CXcoZxRoJBjdU69kVjo7XYU1SFE2NEK4UMqn/workloads?from=308\": dial tcp: lookup explorer.testnet.grid.tf on 1.1.1.1:53: read udp 10.5.0.18:43346->1.1.1.1:53: i/o timeout" next=308
 [+] networkd: 2021-01-14T05:38:47Z info check if ndmz default route is still in place
 [+] provisiond: 2021-01-14T05:38:40Z error failed to get reservation, retry same error="error while retrieving workloads from explorer: Get \"https://explorer.testnet.grid.tf/api/v1/reservations/nodes/8zPYak76CXcoZxRoJBjdU69kVjo7XYU1SFE2NEK4UMqn/workloads?from=308\": dial tcp: lookup explorer.testnet.grid.tf on 1.1.1.1:53: read udp 10.5.0.18:36817->1.1.1.1:53: i/o timeout" next=308
```

Furthermore, the networking is set up for a single nic node on this node, whereas it has 2 physical interfaces. Rebooting the node does not help to solve this problem. Effectively, the second NIC does not receive a SLAAC ip. 

The logs and kernel messages do show that the ip setup for the vm was done properly, meaning the issue is likely related to the lack of network on the host during that moment.

Since a reboot did not help to solve the newtork problem, there might be a misconfiguration on the switchport. Furhter investigation will be done on the node & switch.

In the meantime, I'll leave the issue open for now, in case it occurs again

**Comment by AhmedHanafy725** [comment] 2021-01-17 12:40
it is happening again
**workload:** https://explorer.testnet.grid.tf/api/v1/reservations/workloads/886

![image](https://user-images.githubusercontent.com/41957921/104843019-3bd29e00-58d1-11eb-9760-cc4335ff1f43.png)

![image](https://user-images.githubusercontent.com/41957921/104843096-91a74600-58d1-11eb-8164-41a19331f939.png)

![image](https://user-images.githubusercontent.com/41957921/104843179-e64ac100-58d1-11eb-94f5-47e6cbefbcf7.png)

**Comment by m-motawea** [comment] 2021-01-17 12:51
same for ip https://explorer.testnet.grid.tf/api/v1/reservations/workloads/960
it is not reachable

**Comment by LeeSmet** [comment] 2021-01-18 11:15
@AhmedHanafy725 or @m-motawea can any of you please deploy an instance like this, and not delete it, so I have something to debug/test against?

**Comment by LeeSmet** [comment] 2021-01-18 12:09
As it turns out, there was a misconfigured switch, which broke public setups for testnet nodes. This issue has in the meantime been resolved

**Comment by hossnys** [comment] 2021-01-19 13:59
just have this error again on testnet

![Screenshot from 2021-01-19 15-51-23](https://user-images.githubusercontent.com/26298009/105044087-fea41280-5a6e-11eb-83e8-b05795cadf92.png)


logs 
```
  File "/root/js-sdk/jumpscale/sals/vdc/kubernetes.py", line 357, in download_kube_config                                                                                                                     
    rc, out, err = ssh_client.sshclient.run("cat /etc/rancher/k3s/k3s.yaml", warn=True)                                                                                                                       
                   │          └ <property object at 0x7fe67d25dc20>                                                                                                                                           
                   └ SSHClient(                                                                                                                                                                               
                       instance_name='qatest',                                                                                                                                                                
                       sshkey='qatest',                                                                                                                                                                       
                       host='185.69.167.186',                                                                                                                                                                 
                       user='rancher',                                                                                                                                                                        
                       port=22,                                                                                                                                                                               
                       forward_agent...                                                                                                                                                                       
                                                                                                                                                                                                              
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 65, in run                                                              
    return execute(cmd, command_ctx, self._connection_ctx)                                                                                                                                                    
           │       │    │            │    └ {'host': '185.69.167.186', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'connect_kwargs': {'k...                                  
           │       │    │            └ <jumpscale.core.executors.remote.RemoteExecutor object at 0x7fe677dc9160>                                                                                              
           │       │    └ {'warn': True}                                                                                                                                                                      
           │       └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                          
           └ <function execute at 0x7fe6857173a0>                                                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/command_builder.py", line 28, in inner

    return func(cmd, *args, **kwargs)                                                                                                                                                                         
           │    │     │       └ {}                                                                                                                                                                            
           │    │     └ ({'warn': True}, {'host': '185.69.167.186', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'con...                                                      
           │    └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                             
           └ <function execute at 0x7fe685717280>                                                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 33, in execute                                                          
    res = c.run(cmd, **command_ctx)                                                                                                                                                                           
          │ │   │      └ {'warn': True}                                                                                                                                                                       
          │ │   └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                             
          │ └ <function Connection.run at 0x7fe685734ca0>                                                                                                                                                     
          └ <Connection host=185.69.167.186 user=rancher>                                                                                                                                                     
  File "<decorator-gen-3>", line 2, in run                                                                                                                                                                    
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 29, in opens                                                                          
    self.open()                                                                                                                                                                                               
    │    └ <function Connection.open at 0x7fe685734670>                                                                                                                                                       
    └ <Connection host=185.69.167.186 user=rancher>                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 634, in open                                                                          
    self.client.connect(**kwargs)                                                                                                                                                                             
    │    │      │         └ {'key_filename': '/root/.ssh/id_rsa', 'username': 'rancher', 'hostname': '185.69.167.186', 'port': 22, 'timeout': 10}

    │    │      └ <function SSHClient.connect at 0x7fe68578a5e0>                                                                                                                                              
    │    └ <paramiko.client.SSHClient object at 0x7fe67f553eb0>                                                                                                                                               
    └ <Connection host=185.69.167.186 user=rancher>                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/paramiko/client.py", line 349, in connect                                                                         
    retry_on_signal(lambda: sock.connect(addr))                                                                                                                                                               
    │                       │    │       └ ('185.69.167.186', 22)                                                                                                                                             
    │                       │    └ <function socket.connect at
```

**Comment by hossnys** [comment] 2021-01-19 13:59
just have this error again on testnet

![Screenshot from 2021-01-19 15-51-23](https://user-images.githubusercontent.com/26298009/105044087-fea41280-5a6e-11eb-83e8-b05795cadf92.png)


logs 
```
  File "/root/js-sdk/jumpscale/sals/vdc/kubernetes.py", line 357, in download_kube_config                                                                                                                     
    rc, out, err = ssh_client.sshclient.run("cat /etc/rancher/k3s/k3s.yaml", warn=True)                                                                                                                       
                   │          └ <property object at 0x7fe67d25dc20>                                                                                                                                           
                   └ SSHClient(                                                                                                                                                                               
                       instance_name='qatest',                                                                                                                                                                
                       sshkey='qatest',                                                                                                                                                                       
                       host='185.69.167.186',                                                                                                                                                                 
                       user='rancher',                                                                                                                                                                        
                       port=22,                                                                                                                                                                               
                       forward_agent...                                                                                                                                                                       
                                                                                                                                                                                                              
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 65, in run                                                              
    return execute(cmd, command_ctx, self._connection_ctx)                                                                                                                                                    
           │       │    │            │    └ {'host': '185.69.167.186', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'connect_kwargs': {'k...                                  
           │       │    │            └ <jumpscale.core.executors.remote.RemoteExecutor object at 0x7fe677dc9160>                                                                                              
           │       │    └ {'warn': True}                                                                                                                                                                      
           │       └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                          
           └ <function execute at 0x7fe6857173a0>                                                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/command_builder.py", line 28, in inner

    return func(cmd, *args, **kwargs)                                                                                                                                                                         
           │    │     │       └ {}                                                                                                                                                                            
           │    │     └ ({'warn': True}, {'host': '185.69.167.186', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'con...                                                      
           │    └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                             
           └ <function execute at 0x7fe685717280>                                                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 33, in execute                                                          
    res = c.run(cmd, **command_ctx)                                                                                                                                                                           
          │ │   │      └ {'warn': True}                                                                                                                                                                       
          │ │   └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                             
          │ └ <function Connection.run at 0x7fe685734ca0>                                                                                                                                                     
          └ <Connection host=185.69.167.186 user=rancher>                                                                                                                                                     
  File "<decorator-gen-3>", line 2, in run                                                                                                                                                                    
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 29, in opens                                                                          
    self.open()                                                                                                                                                                                               
    │    └ <function Connection.open at 0x7fe685734670>                                                                                                                                                       
    └ <Connection host=185.69.167.186 user=rancher>                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 634, in open                                                                          
    self.client.connect(**kwargs)                                                                                                                                                                             
    │    │      │         └ {'key_filename': '/root/.ssh/id_rsa', 'username': 'rancher', 'hostname': '185.69.167.186', 'port': 22, 'timeout': 10}

    │    │      └ <function SSHClient.connect at 0x7fe68578a5e0>                                                                                                                                              
    │    └ <paramiko.client.SSHClient object at 0x7fe67f553eb0>                                                                                                                                               
    └ <Connection host=185.69.167.186 user=rancher>                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/paramiko/client.py", line 349, in connect                                                                         
    retry_on_signal(lambda: sock.connect(addr))                                                                                                                                                               
    │                       │    │       └ ('185.69.167.186', 22)                                                                                                                                             
    │                       │    └ <function socket.connect at
```

**Comment by waleedhammam** [comment] 2021-01-19 14:36
workload: ip: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/1693
cluster master: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/1695
ip: 185.69.167.179
ping 
![Screenshot from 2021-01-19 16-36-00](https://user-images.githubusercontent.com/10658229/105048615-6f016280-5a74-11eb-8bc4-b1c198cdcee6.png)


Pool will at: GMT: Wednesday, January 20, 2021 4:37:27 PM

**Comment by LeeSmet** [comment] 2021-01-19 15:55
Ok, so I'm able to recreate the issue using a network namespace + veth pair on the node, which emulates the way the network would behave with the vm. Running this same setup on other nodes does work. On this node, the network setup for some reason does not use both NIC's as it should.

Running a tcpdump shows that no packets are coming into the host.

It seems that the upstream switch is configured to not allow the public traffic on the first NIC, need to verify the exact switch config

**Comment by LeeSmet** [comment] 2021-01-19 16:07
The switch indeed is configured to to only allow vlan 401 on the primary NIC and 301 on the secondary NIC. Incomming public traffic is tagged as vlan 301. Since the network on the node incorectly uses only a single NIC, this explains why its not reachable here

**Comment by dmahmouali** [comment] 2021-01-20 11:27
just have this error on testnet
![image](https://user-images.githubusercontent.com/36021484/105168752-3a001900-5b23-11eb-8604-798c995ef248.png)

#### logs:
```
2021-01-20 11:06:53.860 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:150 - error                                                                             
Traceback (most recent call last):                                                                                                                                      
                                                                                                                                                                        
  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 547, in deploy_vdc                                                                                           
    kube_config = self.kubernetes.download_kube_config(master_ip)                                                                                                       
                  │    │                               └ '185.69.167.185'                                                                                               
                  │    └ <property object at 0x7f80c58edd60>                                                                                                            
                  └ <jumpscale.sals.vdc.deployer.VDCDeployer object at 0x7f80cdc5eac0>                                                                                  
                                                                                                                                                                        
  File "/root/js-sdk/jumpscale/sals/vdc/kubernetes.py", line 357, in download_kube_config                                                                               
    rc, out, err = ssh_client.sshclient.run("cat /etc/rancher/k3s/k3s.yaml", warn=True)                                                                                 
                   │          └ <property object at 0x7f80cc42d950>                                                                                                     
                   └ SSHClient(                                                                                                                                         
                       instance_name='ayoub44',                                                                                                                         
                       sshkey='ayoub44',                                                                                                                                
                       host='185.69.167.185',                                                                                                                           
                       user='rancher',                                                                                                                                  
                       port=22,                                                                                                                                         
                       forward_age...                                                                                                                                   
                                                                                                                                                                        
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 65, in run                        
    return execute(cmd, command_ctx, self._connection_ctx)                                                                                                              
           │       │    │            │    └ {'host': '185.69.167.185', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'connect_kwargs': {'
k...                                                                                                                                                                    
           │       │    │            └ <jumpscale.core.executors.remote.RemoteExecutor object at 0x7f80cc18d9a0>                                                        
           │       │    └ {'warn': True}                                                                                                                                
           │       └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                    
           └ <function execute at 0x7f80cfcbdee0>                                                                                                                       
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/command_builder.py", line 28, in inner             
    return func(cmd, *args, **kwargs)                                                                                                                                   
           │    │     │       └ {}                                                                                                                                      
           │    │     └ ({'warn': True}, {'host': '185.69.167.185', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'con...                
           │    └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                       
           └ <function execute at 0x7f80cfcbddc0>                                                                                                         
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 33, in execute                    
    res = c.run(cmd, **command_ctx)                                                                                                                                     
          │ │   │      └ {'warn': True}                                             
          │ │   └ 'cat /etc/rancher/k3s/k3s.yaml'                                   
          │ └ <function Connection.run at 0x7f80cf19bc10>                                                                                                               
          └ <Connection host=185.69.167.185 user=rancher>                                                                                                               
  File "<decorator-gen-3>", line 2, in run                                          
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 29, in opens
    self.open()                           
    │    └ <function Connection.open at 0x7f80cf19b5e0>                                                                                                                 
    └ <Connection host=185.69.167.185 user=rancher>                                                                                                                     
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 634, in open
    self.client.connect(**kwargs)                                                   
    │    │      │         └ {'key_filename': '/root/.ssh/id_rsa', 'username': 'rancher', 'hostname': '185.69.167.185', 'port': 22, 'timeout': 10}
    │    │      └ <function SSHClient.connect at 0x7f80cf1844c0>                                                                                                        
    │    └ <paramiko.client.SSHClient object at 0x7f80cc111100>                                                                                                         
    └ <Connection host=185.69.167.185 user=rancher>                                                                                                                     
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))                                     
    │                       │    │       └ ('185.69.167.185', 22)                                                                                                       
    │                       │    └ <function socket.connect at 0x7f80d46be8b0>                                                                                          
    │                       └ <gevent._socket3.socket object, fd=65, family=2, type=1, proto=0>
    └ <function retry_on_signal at 0x7f80cfc40940>                                                                                                                      
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/paramiko/util.py", line 283, in retry_on_signal
    return function()                     
           └ <function SSHClient.connect.<locals>.<lambda> at 0x7f80c470a550>                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))                                     
    │                       │    │       └ ('185.69.167.185', 22)                                                                                                       
    │                       │    └ <function socket.connect at 0x7f80d46be8b0>                                                                                          
    │                       └ <gevent._socket3.socket object, fd=65, family=2, type=1, proto=0>
    └ <function retry_on_signal at 0x7f80cfc40940>                                                                                                                      
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/gevent/_socket3.py", line 341, in connect
    self._wait(self._write_event)                                                   
    │    │     │    └ <io at 0x7f80c587a140 fd=65 events=WRITE>                                                                                                         
    │    │     └ <gevent._socket3.socket object, fd=65, family=2, type=1, proto=0>                                                                                      
    │    └ <cyfunction wait_on_socket at 0x7f80d4f5e880>                                                                                                                
    └ <gevent._socket3.socket object, fd=65, family=2, type=1, proto=0>          
```

**Comment by LeeSmet** [comment] 2021-01-20 14:19
We removed the faulty node from testnet for now.

**Comment by hossnys** [comment] 2021-01-21 10:59
just got the same error now on testnet :

active_workload_ids=[2288, 2289, 2290, 2304, 2293, 2294, 2291, 2292, 2303, 2295, 2298, 2296, 2299, 2302, 2301, 2309, 2311, 2310, 2308]

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/2303
node : DJoL9ZV53K5YQurmxor2BLWTPf3WA9dT3RsFWeDeAx1z

logs: 
```
  rc, out, err = ssh_client.sshclient.run("cat /etc/rancher/k3s/k3s.yaml", warn=True)                                                                                                                       
                   │          └ <property object at 0x7f80cc42d950>                                                                                                                                           
                   └ SSHClient(                                                                                                                                                                               
                       instance_name='qatest',                                                                                                                                                                
                       sshkey='qatest',                                                                                                                                                                       
                       host='185.69.167.171',                                                                                                                                                                 
                       user='rancher',                                                                                                                                                                        
                       port=22,                                                                                                                                                                               
                       forward_agent...                                                                                                                                                                       
                                                                                                                                                                                                              
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 65, in run                                                              
    return execute(cmd, command_ctx, self._connection_ctx)                                                                                                                                                    
           │       │    │            │    └ {'host': '185.69.167.171', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'connect_kwargs': {'k...                                  
           │       │    │            └ <jumpscale.core.executors.remote.RemoteExecutor object at 0x7f80c43c1880>                                                                                              
           │       │    └ {'warn': True}                                                                                                                                                                      
           │       └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                          
           └ <function execute at 0x7f80cfcbdee0>                                                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/command_builder.py", line 28, in inner                                                   
    return func(cmd, *args, **kwargs)

           │    │     │       └ {}                                                                                                                                                                            
           │    │     └ ({'warn': True}, {'host': '185.69.167.171', 'user': 'rancher', 'port': 22, 'forward_agent': True, 'connect_timeout': 10, 'con...                                                      
           │    └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                             
           └ <function execute at 0x7f80cfcbddc0>                                                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/jumpscale/core/executors/remote.py", line 33, in execute                                                          
    res = c.run(cmd, **command_ctx)                                                                                                                                                                           
          │ │   │      └ {'warn': True}                                                                                                                                                                       
          │ │   └ 'cat /etc/rancher/k3s/k3s.yaml'                                                                                                                                                             
          │ └ <function Connection.run at 0x7f80cf19bc10>                                                                                                                                                     
          └ <Connection host=185.69.167.171 user=rancher>                                                                                                                                                     
  File "<decorator-gen-3>", line 2, in run                                                                                                                                                                    
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 29, in opens                                                                          
    self.open()                                                                                                                                                                                               
    │    └ <function Connection.open at 0x7f80cf19b5e0>                                                                                                                                                       
    └ <Connection host=185.69.167.171 user=rancher>                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/fabric/connection.py", line 634, in open                                                                          
    self.client.connect(**kwargs)                                                                                                                                                                             
    │    │      │         └ {'key_filename': '/root/.ssh/id_rsa', 'username': 'rancher', 'hostname': '185.69.167.171', 'port': 22, 'timeout': 10}                                                             
    │    │      └ <function SSHClient.connect at 0x7f80cf1844c0>

    │    └ <paramiko.client.SSHClient object at 0x7f80cc2c4580>                                                                                                                                               
    └ <Connection host=185.69.167.171 user=rancher>                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/paramiko/client.py", line 368, in connect                                                                         
    raise NoValidConnectionsError(errors)                                                                                                                                                                     
          │                       └ {('185.69.167.171', 22): OSError(113, 'No route to host')}                                                                                                                
          └ <class 'paramiko.ssh_exception.NoValidConnectionsError'>                         
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step                                                                                                     [156/1101]
    wrapper(step_name)                                                                                                                                                                                        
    │       └ 'deploy'                                                                                                                                                                                            └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f80d0a18ca0>                                                                                                                                                                                                                                                                                                                                      > File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper                                                                                                                             
    getattr(self, step_name)()                                                                                                                                                                                
            │     └ 'deploy'                                                                                                                                                                                              └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f80cda839d0>                                                                                                                                                                                                                                                                                                                                                          File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper                                                                                                                             
    return func(*args, **kwargs)

           │     │       └ {}                                                                                                                                                                                            │     └ (<vdc.chats.new_vdc.VDCDeploy object at 0x7f80cda839d0>,)                                                                                                                                             └ <function VDCDeploy.deploy at 0x7f80c5a39ee0>                                                                                                                                                                                                                                                                                                                                                                  
  File "/root/js-sdk/jumpscale/packages/vdc/chats/new_vdc.py", line 141, in deploy                                                                                                                            
    self.stop(str(err))                                                                                                                                                                                           │    └ <function GedisChatBot.stop at 0x7f80c62f3280>                                                                                                                                                         └ <vdc.chats.new_vdc.VDCDeploy object at 0x7f80cda839d0>                                                                                                                                                                                                                                                                                                                                                                
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 657, in stop                         
    raise StopChatFlow(msg=msg, **kwargs)                                                                                                                                                                               │            │   │      └ {}                                                                                                                                                                                  │            │   └ 'failed to download kube config due to error [Errno None] Unable to connect to port 22 on 185.69.167.171'                                                                                  │            └ 'failed to download kube config due to error [Errno None] Unable to connect to port 22 on 185.69.167.171'                                                                            
          └ <class 'jumpscale.sals.chatflows.chatflows.StopChatFlow'>                                                                                                                                         
                                                                                                                                                                                                              jumpscale.sals.chatflows.chatflows.StopChatFlow: (StopChatFlow(...), 'failed to download kube config due to error [Errno None] Unable to connect to port 22 on 185.69.167.171')
```

**Comment by LeeSmet** [comment] 2021-01-21 11:19
@hossnys please add relevant reservation ids please

**Comment by LeeSmet** [comment] 2021-01-21 11:34
so this node the deployment is on suffers from the same issue as the previously removed node (dual nic node, which runs in single nic setup)

**Comment by LeeSmet** [comment] 2021-01-21 11:36
On this node there are some other vms with public IP's however, and those do work. Making a manual setup with a namespace and a veth attached to br-pub also suggests we have public accessibility on this node

**Comment by LeeSmet** [comment] 2021-01-21 13:44
Offending node has also been powered down for now, networkd will need to be adapted to give more time for SLAAC to finish

**Comment by m-motawea** [comment] 2021-01-21 14:00
> Offending node has also been powered down for now, networkd will need to be adapted to give more time for SLAAC to finish

does this mean we can validate the node before deployment if all physical ifaces are assigned an IPv6 address?
![image](https://user-images.githubusercontent.com/32568986/105360851-ba954700-5c01-11eb-8a8b-ad38d8005935.png)

**Comment by LeeSmet** [comment] 2021-01-21 14:04
@m-motawea sadly no, IPv6 needs to be disabled on the physical interfaces. The problem is that network setup makes certain assumptions about the way the nodes route traffic, which are currently not upheld by these nodes

**Comment by LeeSmet** [comment] 2021-01-21 14:08
tracking issue for decent fix: https://github.com/threefoldtech/zos/issues/1159

**Comment by LeeSmet** [comment] 2021-01-22 15:27
2 nodes that we downed have been rebooted after #1162 landed. Network setup now looks good on those. Will power cycle all testnet nodes tonight so we are sure all of them have proper network setup

**Comment by xmonader** [comment] 2021-02-25 21:08
The issue is back again 

![image](https://user-images.githubusercontent.com/64129/109217214-3b75ce80-77be-11eb-8abc-f5f0422ca4b3.png)

- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/33014
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/32935
- https://explorer.devnet.grid.tf/api/v1/reservations/workloads/33061

**Comment by LeeSmet** [comment] 2021-02-25 22:21
@xmonader all 3 listed ips work for me, I can ping them and ssh server replies if I ssh them (`rancher@185.69.167.12{3,5,9}`)

**Comment by xmonader** [comment] 2021-02-25 22:25
@LeeSmet with more further investigation this is raised when we can't read (k3s.yml file) or reach the vm over ssh. 

![image](https://user-images.githubusercontent.com/64129/109227260-b348f680-77c8-11eb-9f37-fbf93b315f65.png)

the k3s.yml is gone only k3s-service.env exists. If you'd like feel free to close this issue and open another one for k3s.yml being missing

**Comment by xmonader** [comment] 2021-02-25 22:36
@LeeSmet: @AhmedHanafy725 found the problem, was the external etcds crashing. I'll move it back to verification thanks.

**Comment by sasha-astiadi** [comment] 2021-03-12 11:34
@xmonader hi can we close this now ?

**Comment by AhmedHanafy725** [comment] 2021-04-26 15:02
happened again 
pubic_ip: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/35188
k8s: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/35189

**Comment by waleedhammam** [comment] 2021-04-29 14:13
I got Failed to download kube config due to error timed out twice on a row
master: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/48351
public ip:  `185.69.167.55/24` node id: `2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP`

**Comment by sasha-astiadi** [comment] 2021-05-06 13:50
sny update @LeeSmet

**Comment by LeeSmet** [comment] 2021-05-06 14:03
CH has been updated with a patch, and devnet machines have been rebooted so the CH patch is reflected. We assume this will fix the issue.

**Closed as completed** 2021-05-11 16:42 UTC
Labels: type_bug
