### ISSUE TITLE
provisiond: network not cleaned correctly if container provision fails

### ISSUE THREAD

**Issue by maxux** [threefoldtech/zos#967] opened 2020-09-23 09:03 UTC
It looks like when a container cannot be started for some reason (here, OCI issue, but that's not the issue), network is not cleaned up after the error:

```
[+] contd: 2020-09-23T08:56:37Z error logger new task error="OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/ns41/1619-1/log.json: no such file or directory): runc did not terminate successfully: unknown"
[-] containerd: time="2020-09-23T08:56:37.344544998Z" level=info msg="shim disconnected" id=1619-1
[-] containerd: time="2020-09-23T08:56:37.345376509Z" level=debug msg="event published" ns=ns41 topic=/containers/delete type=containerd.events.ContainerDelete
[+] provisiond: 2020-09-23T08:56:37Z error error during delete of container error="container \"1619-1\" in namespace \"ns41\": not found" container_id=1619-1
[+] flistd: 2020-09-23T08:56:37Z info request unmount flist path=/var/cache/modules/flistd/mountpoint/1619-1
[-] containerd: time="2020-09-23T08:56:37.348323849Z" level=debug msg="garbage collected" d="71.819µs"
[+] storaged: 2020-09-23T08:56:37Z info Deleting volume 1619-1
[+] storaged: 2020-09-23T08:56:37Z debug Removing filesystem 1619-1 in volume ca8d2b1a-c97e-474c-835a-e448217a8dab
[+] storaged: 2020-09-23T08:56:37Z warn Could not find filesystem 1619-1
[+] networkd: 2020-09-23T08:56:37Z info leaving network network-id=WpH7mvHYooCpo
[+] networkd: 2020-09-23T08:56:37Z info delete container network namespace container=1619-1 namespace=1619-1
[+] provisiond: 2020-09-23T08:56:37Z error failed leave container network namespace error="failed to unmount NS: at /var/run/netns/1619-1: device or resource busy"
[+] provisiond: 2020-09-23T08:56:37Z error failed to apply provision error="error starting container: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/ns41/1619-1/log.json: no such file or directory): runc did not terminate successfully: unknown" id=1619-1
[+] provisiond: 2020-09-23T08:56:37Z error failed to provision reservation 1619-1 error="error starting container: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/ns41/1619-1/log.json: no such file or directory): runc did not terminate successfully: unknown"
```

The new `veth` interface is still present after error.

**Comment by zaibon** [comment] 2020-09-30 12:30
Hum from the logs and the code flow, it seems the container is properly gone, so I'm really not sure what could still be holding a reference into the network namespace of the container that prevent it to be cleaned up.

**Comment by delandtj** [comment] 2020-10-22 08:18
zinit or another process?

**Comment by zaibon** [comment] 2020-10-22 08:45
so you suspect the containerd-shim would somehow reattach to zinit process ? Sounds weird to me.

**Comment by DylanVerstraete** [comment] 2020-12-08 12:54
Last occurrence was a while ago. Closing because we cannot reproduce.

![Screenshot from 2020-12-08 13-36-15](https://user-images.githubusercontent.com/17138347/101486191-8f5ddd80-395c-11eb-8b3e-88cde0378f4c.png)

**Closed as completed by DylanVerstraete** 2020-12-08 12:54 UTC
Labels: type_bug
