### ISSUE TITLE
k8s: no error in reservation result when deploying 2 member of the same cluster on the same node

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#647] opened 2020-03-30 09:06 UTC
### Steps
1- Create network
```python
zos = j.sal.zosv2
r = zos.reservation_create()
network = zos.network.create(r, ip_range="10.237.0.0/16", network_name="test")
nodes = zos.nodes_finder.nodes_search(farm_name="freefarm")
node_ipv6 = next(filter(zos.nodes_finder.filter_public_ip6, nodes)) 
node_ipv4 = next(filter(zos.nodes_finder.filter_public_ip4, nodes))
zos.network.add_node(network, node_ipv4.node_id, "10.237.94.0/24")
zos.network.add_node(network, node_ipv6.node_id, "10.237.98.0/24")
wg_config = zos.network.add_access(network, node_ipv4.node_id, "10.237.200.0/24", ipv4=True)
expiration = j.data.time.epoch + (3600 * 24)
network_rid = zos.reservation_register(r, expiration)
zos.reservation_result(network_rid)
```
2- Make sure that there is no error in this result
3- Create k8s cluster with one master and one worker on the same node.
```python
zos = j.sal.zosv2
r = zos.reservation_create()
master = zos.kubernetes.add_master(reservation=r, node_id=node_ipv6.node_id, network_name="test", cluster_secret="test_k8s", ip_address="10.237.98.21", size=1, ssh_keys=<sshkeys>)
worker = zos.kubernetes.add_worker(reservation=r, node_id=node_ipv6.node_id ,network_name="test", cluster_secret="test_k8s", ip_address="10.237.98.22", size=1, master_ip="10.237.98.21", ssh_keys=<sshkeys>)
kubers_rid = zos.reservation_register(r, expiration)
zos.reservation_result(kubers_id) 
```
### Expected Result
Error in the result when nothing is deployed.

### Actual Result
Everything is OK and no error.

```                                                                                    
JSX> result = zos.reservation_result(kubers_id)                                                                                                
JSX> result                                                                                                                                    
    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/29 14:47:20"
    message = ""
    signature = "7513904ab834b4217e8ee6a811a6bdd4b439b59e603cad6f3b66edd9b84007eebebb12dee1597ff52104596af5c1c582ebaeda33f6693a4b034a1cfcc8464000"
    state = "OK"
    workload_id = "458415-1"

    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/29 14:47:24"
    message = ""
    signature = "5dc91d1e6fa90d480ff81c96366f3ab0b809994902365e89d8186b4c1bb53895f5318492ac0847701fd0d82aa000258a8daf957dbae975bbc5e5f59f43335409"
    state = "OK"
    workload_id = "458415-1"

    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/29 14:47:24"
    message = ""
    signature = "a5916fb536f1d3c92b89a5a610753fbe16ebfd2e86d303b9d8f318959483c31817fc8b5efa5420b40ec268948d9cb6d8320e3479edc5fb2b159ed84e9a00f505"
    state = "OK"
    workload_id = "458415-1"

```

**Comment by AhmedHanafy725** [comment] 2020-03-31 09:04
## Also no error in result when deploying cluster on two different nodes and it doesn't work.
### Steps
1- Create network
```python
zos = j.sal.zosv2
r = zos.reservation_create()
network = zos.network.create(r, ip_range="10.239.0.0/16", network_name="zeroci_24")
nodes = zos.nodes_finder.nodes_search(farm_name="freefarm")
node_ipv4 = next(filter(zos.nodes_finder.filter_public_ip4, nodes))
node_ipv6_1 = nodes[6]
node_ipv6_2 = nodes[7]
zos.network.add_node(network, node_ipv4.node_id, "10.239.94.0/24")
zos.network.add_node(network, node_ipv6_1.node_id, "10.239.96.0/24")
zos.network.add_node(network, node_ipv6_2.node_id, "10.239.97.0/24")
wg_config = zos.network.add_access(network, node_ipv4.node_id, "10.239.199.0/24", ipv4=True)
expiration = j.data.time.epoch + (3600 * 24* 365)
network_rid = zos.reservation_register(r, expiration)
result = zos.reservation_result(network_rid)
```
2- Make sure that there is no error in this result.
```
JSX> result                                                                                                                                    
    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/30 09:14:21"
    message = ""
    signature = "e34a643d1c97211af5231373981ce392e95f3483f98187df4a737ea25e495f51186032e3ed8bd62ffb1a36fec0eab6e44032e00d15de13a73b32a2449666ef00"
    state = "OK"
    workload_id = "458440-1"

    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/30 09:14:21"
    message = ""
    signature = "7513904ab834b4217e8ee6a811a6bdd4b439b59e603cad6f3b66edd9b84007eebebb12dee1597ff52104596af5c1c582ebaeda33f6693a4b034a1cfcc8464000"
    state = "OK"
    workload_id = "458440-1"

    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/30 09:14:26"
    message = ""
    signature = "c682612eb760b7c85a9a658882b3561ef7b7e3f7283ee6074dca2cef44fa5b0fd601d470e5a5fd89664ac2a15c48efed345020e88e0a7a467518c23b74b5c600"
    state = "OK"
    workload_id = "458440-1"

JSX> network_rid                                                                                                                                
458440

```
3- Create k8s cluster with one master and one worker on two different nodes.
```python
zos = j.sal.zosv2
r = zos.reservation_create()
master = zos.kubernetes.add_master(reservation=r, node_id=node_ipv6_1.node_id, network_name="zeroci_24", cluster_secret="test_k8s", ip_address="10.239.96.30", size=1, ssh_keys=<sshkeys>)
worker = zos.kubernetes.add_worker(reservation=r, node_id=node_ipv6_2.node_id ,network_name="zeroci_24", cluster_secret="test_k8s", ip_address="10.239.97.31", size=1, master_ip="10.239.96.30", ssh_keys=<sshkeys>)
kubers_rid = zos.reservation_register(r, expiration)
result = zos.reservation_result(kubers_rid)
```
### Expected Result
Error in the result when nothing is deployed.

### Actual Result
Everything is OK and no error.

```
JSX> result                                                                                                                                    
    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/30 09:17:21"
    message = ""
    signature = "e34a643d1c97211af5231373981ce392e95f3483f98187df4a737ea25e495f51186032e3ed8bd62ffb1a36fec0eab6e44032e00d15de13a73b32a2449666ef00"
    state = "OK"
    workload_id = "458443-1"

    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/30 09:17:21"
    message = ""
    signature = "7513904ab834b4217e8ee6a811a6bdd4b439b59e603cad6f3b66edd9b84007eebebb12dee1597ff52104596af5c1c582ebaeda33f6693a4b034a1cfcc8464000"
    state = "OK"
    workload_id = "458443-1"

    category = "NETWORK"
    data_json = "{}"
    epoch = "2020/03/30 09:17:26"
    message = ""
    signature = "c682612eb760b7c85a9a658882b3561ef7b7e3f7283ee6074dca2cef44fa5b0fd601d470e5a5fd89664ac2a15c48efed345020e88e0a7a467518c23b74b5c600"
    state = "OK"
    workload_id = "458443-1"

JSX> kubers_rid
458443
```

**Comment by DylanVerstraete** [comment] 2020-10-01 08:34
@zaibon is this a duplicate of https://github.com/threefoldtech/zos/issues/881?

**Comment by DylanVerstraete** [comment] 2021-03-05 09:30
Closing because this is not a blocking issue anymore.

**Closed as completed by DylanVerstraete** 2021-03-05 09:30 UTC
Labels: type_bug
