### ISSUE TITLE
cp doesn't work on a node in freefarm

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#969] opened 2020-09-23 12:28 UTC
These workloads got deployed successfully but they were not doing what they were supposed to do. After sshing into the container the cp command fails with this error:

`cp: skipping file '/config/nginx.conf', as it was replaced while being copied`

`touch /config/nginx.conf` then copying works.

It happened only on the node A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7. It doesn't appear on other nodes.

workloads: [486320](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/486320) [486197](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/486197)

**Comment by xmonader** [comment] 2020-09-23 16:04
this one also seems related 
12663
12665
12664
12666

node id : Ddstj2hPbGip8Ci26TUaEzY52DHZs3JphLFXy9UgWSRS

waleedhammam-peertube-byebola.tfgw-prod-06.gateway.tf

**Comment by xmonader** [comment] 2020-09-24 07:40
seems to be the same on 2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6  
- wids: 486575, 486577, 486576, 486578 
- ahmedthabet-peertube-pv.tfgw-testnet-01.ava.tf
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/486594

http://ahmedthabet-peertube-pv.tfgw-testnet-01.ava.tf


and also when tried mattermost
- wids: 486590, 486593, 486592, 486594
- node 6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ 
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/486578
http://ahmedthabet-mattermost-mza.tfgw-testnet-01.gateway.tf

**Comment by muhamadazmy** [comment] 2020-09-24 07:47
Okay, it seems i can reproduce on my system! This looks like a regression bug of some sort, because this did not happen before

**Comment by muhamadazmy** [comment] 2020-09-24 11:04
Should be fixed by: https://github.com/threefoldtech/zos/pull/971

**Comment by OmarElawady** [comment] 2020-09-29 10:13
Reproduced on mainnet:
![Screenshot from 2020-09-29 11-33-25](https://user-images.githubusercontent.com/13040543/94545645-1a2fa700-024d-11eb-906f-317c35743c21.png)
Node: Ddstj2hPbGip8Ci26TUaEzY52DHZs3JphLFXy9UgWSRS
wid: 14391

**Comment by muhamadazmy** [comment] 2020-09-29 10:38
We did not release this fix on mainnet yet. Last release (with the fix) is a "pre-release" which means it only available on testnet

**Comment by muhamadazmy** [comment] 2020-09-29 10:39
Ops, my mistake, it seems we have released for mainnet. let me check if the update made it

**Comment by muhamadazmy** [comment] 2020-09-29 10:43
I checked the nodes, and idd this node does not have the latest 0-fs with the fix. Checking why

**Comment by muhamadazmy** [comment] 2020-09-29 11:05
Latest update: it seems we indeed release the fix for mainnet, but for some reason, it seems the version was not updated on the hub correctly for mainnet. hence all nodes on mainnet do not have the fix.

**Comment by zaibon** [comment] 2020-09-29 14:32
I force push the latest version on mainnet. @OmarElawady can you validate that new container do not have this issue anymore ?

**Comment by OmarElawady** [comment] 2020-09-29 15:33
I tried it now and it works. workload 15121
![Screenshot from 2020-09-29 17-32-48](https://user-images.githubusercontent.com/13040543/94580121-d1daae00-0279-11eb-8b76-3b58ff27669f.png)

**Closed as completed** 2020-09-29 15:56 UTC
Labels: type_bug
