### ISSUE TITLE
document upgrade module

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2311] opened 2024-05-07 17:14 UTC
https://github.com/threefoldtech/zos/blob/aba91356682689746a9e073b687aa6c881df6bfd/pkg/upgrade

**Comment by ashraffouda** [comment] 2024-06-02 09:15
duplicate of https://github.com/threefoldtech/zos/issues/2187

**Closed as completed by ashraffouda** 2024-06-02 09:15 UTC
Labels: type_feature
