### ISSUE TITLE
networkd: failed to remove file mapping between network ID and namespace 

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#700] opened 2020-04-11 16:16 UTC
```
[+] networkd: 2020-04-11T16:15:49Z error failed to remove file mapping between network ID and namespace error="remove /var/run/cache/networkd/networks/GTNJdF9RL2L98: no such file or directory"
```

**Comment by DylanVerstraete** [comment] 2020-10-01 08:36
How to reproduce?

**Comment by zaibon** [comment] 2020-10-01 10:18
No idea yet. That was a log I saw one time while looking at them. I wasn't trying to do anything special.

**Comment by DylanVerstraete** [comment] 2021-03-05 10:39
Closing because it's not relevant anymore with the current codebase

**Closed as completed by DylanVerstraete** 2021-03-05 10:39 UTC
Labels: type_bug
